export const ALL_QUESTIONS = [
  { q: '¿Qué método HTTP usás para CREAR un recurso nuevo?', opts: ['GET: Obtiene los recursos actuales', 'POST: Envía datos para crear el recurso', 'PUT: Modifica un recurso parcialmente', 'DELETE: Oculta el recurso del sistema'], correct: 'POST: Envía datos para crear el recurso', explain: 'POST crea recursos nuevos. Cada POST puede crear un recurso diferente (no es idempotente).' },
  { q: 'Recibís un error 401. ¿Qué significa?', opts: ['El servidor no encontró el recurso solicitado', 'No enviaste credenciales válidas de autenticación', 'Ocurrió un error interno en el servidor', 'Excediste el límite de peticiones permitidas'], correct: 'No enviaste credenciales válidas de autenticación', explain: '401 = Unauthorized. No proporcionaste credenciales válidas. Diferente de 403 (tenés credenciales pero no permiso).' },
  { q: '¿Cuál de estos JSON es VÁLIDO?', opts: ["{ nombre: 'test', activo: true }", '{ "nombre": "test", "activo": true }', "{ 'nombre': 'test', 'activo': true }", '{ "nombre": test, "activo": true }'], correct: '{ "nombre": "test", "activo": true }', explain: 'En JSON, las keys y strings SIEMPRE van con comillas dobles (").' },
  { q: '¿Qué header se usa para indicar el formato del body?', opts: ['Authorization: Bearer <token>', 'Content-Type: application/json', 'Accept: application/json', 'User-Agent: Mozilla/5.0'], correct: 'Content-Type: application/json', explain: 'Content-Type dice qué formato ENVÍAS (ej: application/json). Accept dice qué formato QUERÉS recibir.' },
  { q: 'Error 404 vs 403: ¿cuál es la diferencia?', opts: ['404 = error del servidor, 403 = error del cliente', '404 = el recurso no existe, 403 = no tenés permiso', '403 = el recurso no existe, 404 = no tenés permiso', '404 = recurso movido, 403 = recurso eliminado'], correct: '404 = el recurso no existe, 403 = no tenés permiso', explain: '404 = el recurso no existe. 403 = existe pero no tenés permiso para accederlo.' },
  { q: '¿Cuál es la diferencia entre PUT y PATCH?', opts: ['PUT crea un recurso nuevo, PATCH solo lo elimina', 'PUT reemplaza el recurso entero, PATCH solo partes', 'PATCH actualiza datos sincrónicamente, PUT es async', 'PUT es más seguro para datos, PATCH es más rápido'], correct: 'PUT reemplaza el recurso entero, PATCH solo partes', explain: 'PUT reemplaza el recurso completo. PATCH actualiza solo los campos que enviás. PUT necesita el objeto completo.' },
  { q: "¿Qué significa que GET es 'idempotente'?", opts: ['Es el método más rápido para obtener información', 'Llamarlo una o mil veces produce el mismo estado', 'Solo se puede ejecutar una vez por cada sesión', 'No requiere autenticación para devolver datos'], correct: 'Llamarlo una o mil veces produce el mismo estado', explain: 'Idempotente = llamarlo 1 vez o 100 da el mismo resultado. GET, PUT y DELETE son idempotentes. POST no.' },
  { q: 'Recibís un 429. ¿Qué hacés?', opts: ['Reintentar la petición inmediatamente de forma cíclica', 'Implementar exponential backoff y reintentar luego', 'Cambiar de endpoint para evadir el bloqueo actual', 'Renovar el token de autenticación inmediatamente'], correct: 'Implementar exponential backoff y reintentar luego', explain: '429 = Too Many Requests (rate limit). La estrategia correcta es exponential backoff: esperar cada vez más entre reintentos.' },
  { q: '¿Cuál es el código de estado para un éxito estándar en GET?', opts: ['200 OK: La solicitud tuvo éxito', '201 Created: El recurso fue creado', '204 No Content: Éxito sin respuesta', '400 Bad Request: Todo correcto'], correct: '200 OK: La solicitud tuvo éxito', explain: 'El código 200 indica que la petición se procesó con éxito y el servidor devuelve la información.' },
  { q: '¿Qué hace el método DELETE?', opts: ['Elimina un recurso de forma permanente o lógica', 'Oculta el recurso temporalmente al usuario', 'Borra el token de autenticación del cliente', 'Elimina los encabezados HTTP del request'], correct: 'Elimina un recurso de forma permanente o lógica', explain: 'DELETE se utiliza para eliminar un recurso. Es idempotente, borrarlo 10 veces seguidas da el mismo resultado (el recurso no existe).' },
  { q: '¿Qué código indica que el servidor falló internamente?', opts: ['400 Bad Request', '404 Not Found', '500 Internal Server Error', '502 Bad Gateway'], correct: '500 Internal Server Error', explain: '500 indica que ocurrió un error inesperado en el servidor y no pudo procesar la solicitud (ej. error de código, caída de DB).' },
  { q: '¿Para qué sirve el endpoint en una API?', opts: ['Es el formato de datos de la respuesta', 'Es la URL específica donde vive el recurso', 'Es el método de autenticación del usuario', 'Es el código de estado del servidor'], correct: 'Es la URL específica donde vive el recurso', explain: 'El endpoint es la ruta (URL) que representa al recurso, por ejemplo: /api/usuarios/1' },
]
